// eslint-disable-next-line import/prefer-default-export
export const USER_LOGIN_INITIATE = 'USER_LOGIN_INITIATE';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

// Clinic Details
export const CLINIC_DETAILS_TOGGLE_EDIT_MODAL = 'CLINIC_DETAILS_TOGGLE_EDIT_MODAL';
export const SAVE_EDIT_DETAILS_INITIALIZE = 'SAVE_EDIT_DETAILS_INITIALIZE';
export const SAVE_EDIT_DETAILS_SUCCESS = 'SAVE_EDIT_DETAILS_SUCCESS';
export const SAVE_EDIT_DETAILS_FAILURE = 'SAVE_EDIT_DETAILS_FAILURE';
export const CLINIC_DETAILS_TOGGLE_ADD_MODAL = 'CLINIC_DETAILS_TOGGLE_ADD_MODAL';
export const SAVE_ADD_DETAILS_INITIALIZE = 'SAVE_ADD_DETAILS_INITIALIZE';
export const SAVE_ADD_DETAILS_SUCCESS = 'SAVE_ADD_DETAILS_SUCCESS';
export const SAVE_ADD_DETAILS_FAILURE = 'SAVE_ADD_DETAILS_FAILURE';
export const DOCTOR_LISTS = 'DOCTOR_LISTS';
export const MEDICAL_ASSISTANTS_LISTS = 'MEDICAL_ASSISTANTS_LISTS';
export const RECEPTIONIST_LISTS = 'RECEPTIONIST_LISTS';
